services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
             bundle exec rails db:environment:set RAILS_ENV=development &&
             bundle exec rails db:drop &&
             bundle exec rails db:create &&
             bundle exec rails db:migrate &&
             bundle exec rails db:seed &&
             bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/embarca-challenge
    ports:
      - "3000:3000"
    depends_on:
      - db
